### ISSUE TITLE
Exception in language server System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by olstakh** [faldor20/fsharp-language-server#17]
I feel like it's something trivial, but can't put my finger on it

```
dotnet new console --language "f#" --name dummy
code -r dummy
```

Output -> F# Language server logs:

```
starting
Logging started
./logs/debugLog-12-10_22;19-28s--.log
logger created
[22:19:28 INF] info log
[22:19:28 WRN] warn log
[22:19:28 ERR] erroor log
fist log should have happened
[22:19:28 INF] created new Project Manager
[22:19:28 WRN] Couldn't find FSharp.Core.dll in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.25
[22:19:28 WRN] Couldn't find System.ComponentModel.Composition.dll in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.25
[22:19:28 WRN] Couldn't find System.Runtime.InteropServices.WindowsRuntime.dll in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.25
[22:19:29 INF] Add workspace root c:\code\dummy
[22:19:29 INF] returning capabilities
[22:19:29 INF] Running inititialization
[22:19:29 INF] New configuration { settings =
   {
  "fsharp": {
    "trace": {
      "server": "off"
    },
    "debug": {
      "enable": false
    },
    "customCommand": null,
    "customCommandArgs": null,
    "customDllPath": null
  }
}}
[22:19:29 INF] No cracked project references Program.fs, looking at uncracked projects...
[22:19:29 INF] The text of dummy.fsproj contains the string Program.fs', cracking
[22:19:29 INF] Analyzing dummy.fsproj
[22:19:29 INF] No up to date cached projectOptions file found for 'C:\code\dummy\dummy.fsproj', cracking normally 
[22:19:30 ERR] Exception in language server System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Ionide.ProjInfo.ProjectLoader.loadProject(String path, BinaryLogGeneration binaryLogs, FSharpList`1 globalProperties)
   at <StartupCode$Ionide-ProjInfo>.$Library.loadProject@825(WorkspaceLoader __, FSharpList`1 customProperties, BinaryLogGeneration binaryLogs, Dictionary`2 cache, String p) in D:\a\proj-info\proj-info\src\Ionide.ProjInfo\Library.fs:line 826
   at <StartupCode$Ionide-ProjInfo>.$Library.loadProjectList@853(WorkspaceLoader __, FSharpList`1 customProperties, BinaryLogGeneration binaryLogs, Dictionary`2 cache, FSharpList`1 projectList) in D:\a\proj-info\proj-info\src\Ionide.ProjInfo\Library.fs:line 863
   at Ionide.ProjInfo.WorkspaceLoader.Ionide.ProjInfo.IWorkspaceLoader.LoadProjects(FSharpList`1 projects, FSharpList`1 customProperties, BinaryLogGeneration binaryLogs) in D:\a\proj-info\proj-info\src\Ionide.ProjInfo\Library.fs:line 871
   at ProjInfo.crack(String path) in C:\Users\edowling\Desktop\code\FSharp\fsharp-language-server\src\ProjInfo\Library.fs:line 35
   at FSharpLanguageServer.ProjectManager.Manager.analyzeWithProjInfo@329(ProjectManager this, FileInfo fsproj) in C:\Users\edowling\Desktop\code\FSharp\fsharp-language-server\src\FSharpLanguageServer\ProjectManager\ProjectManager.fs:line 342
   at FSharpLanguageServer.ProjectManager.Manager.clo@359-1.Invoke(Unit unitVar) in C:\Users\edowling\Desktop\code\FSharp\fsharp-language-server\src\FSharpLanguageServer\ProjectManager\ProjectManager.fs:line 359
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at FSharpLanguageServer.ProjectManager.Manager.crackLazily@482.GenerateNext(IEnumerable`1& next) in C:\Users\edowling\Desktop\code\FSharp\fsharp-language-server\src\FSharpLanguageServer\ProjectManager\ProjectManager.fs:line 495
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 372
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 404
   at Microsoft.FSharp.Collections.SeqModule.TryHead[T](IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1370
   at FSharpLanguageServer.ProjectManager.Manager.ProjectManager.FindProjectOptions(FileInfo sourceFile) in C:\Users\edowling\Desktop\code\FSharp\fsharp-language-server\src\FSharpLanguageServer\ProjectManager\ProjectManager.fs:line 498
   at FSharpLanguageServer.Program.Server.needsRecompile(FileInfo goal) in C:\Users\edowling\Desktop\code\FSharp\fsharp-language-server\src\FSharpLanguageServer\Program.fs:line 301
   at FSharpLanguageServer.Program.LSP-Types-ILanguageServer-DidOpenTextDocument@598.Invoke(Unit unitVar) in C:\Users\edowling\Desktop\code\FSharp\fsharp-language-server\src\FSharpLanguageServer\Program.fs:line 602
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 446
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 391
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1044
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1070
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1365
   at LSP.LanguageServer.connect(FSharpFunc`2 serverFactory, BinaryReader receive, BinaryWriter send, Boolean debugAttach) in C:\Users\edowling\Desktop\code\FSharp\fsharp-language-server\src\LSP\LanguageServer.fs:line 238
   at FSharpLanguageServer.Program.main(String[] argv) in C:\Users\edowling\Desktop\code\FSharp\fsharp-language-server\src\FSharpLanguageServer\Program.fs:line 948
[22:19:32 INF] Cancelling request 5
```

```
PS C:\code\dummy> dotnet --list-sdks
6.0.417 [C:\Program Files\dotnet\sdk]
7.0.404 [C:\Program Files\dotnet\sdk]
```

```
PS C:\code\dummy> dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Building/running dummy project works fine, but language server seems to be crashing every time

**Comment by faldor20** [comment]
This project has no support for dotnet 7.0 unfortunately. I suggest you check out "ionide". I'm nota working on this anymore and I should really archive the repo. Ionide is in a great state these days and you should definitely just use that. Good luck :)

**Comment by olstakh** [comment]
Ah, got it, thanks for the project tho, @faldor20

**Comment by faldor20** [comment]
No worries, thanks for a really good bug report! 
I hope you're enjoying using fsharp :)

I don't write any fsharp these days, but I do a fair bit of Ocaml, which is close enough!
